version: "3.9"

services:
  api:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  web:
    build: ./frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api