version: "3.9"

services:
  api:
    build:
      context: ./backend      # <— build from backend directory
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - backend/.env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app        # <— live-mount backend for dev

  web:
    build: ./frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api